juyonLee00/Text2DBattleGame

Text2DBattleGame/Characters.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Text2DBattleGame.csproj
Program에 있던 캐릭터를 따로 클래스 팠습니당
그리고 배틀 디스플레이 함수 새로 만들었습니다
=> [feat] 캐릭터,몬스터 인터페이스 생성

Text2DBattleGame/Program.cs
=> [refactor] 재귀호출 막기위한 껍데기 수정

Text2DBattleGame/Characters.cs, Text2DBattleGame/DungeonResult.cs
=> [feat]DungeonResult 기본 베이스

Text2DBattleGame.sln, Text2DBattleGame/Characters.cs, Text2DBattleGame/DungeonResult.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Text2DBattleGame.csproj
=> [feat]아이템 클래스 추가

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Text2DBattleGame.csproj
배틀기능 아직 수정할 부분이 있지만 진행은 되는 코드입니다
다만 아직 다른 씬으로 넘어가는 부분을 구현하지 못했습니다
=> [feat] 배틀 기능 추가, 캐릭터의 최대체력과 현재던전레벨 추가

Text2DBattleGame/DisplayBattle.cs
=> [feat] 배틀기능 씬이동 구현

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/DungeonResult.cs
=> [feat]DungeonResult 적용

Text2DBattleGame/DisplayBattle.cs
다시 씬 이동 기능이 없어졌길래 그냥 가장 최신꺼에 붙여서 올렸습니다
=> [feat] 배틀기능 씬구현

Text2DBattleGame/Characters.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Start.cs
- 플레이어 이름과 직업을 선택해서 입력받습니다.
- 공백을 입력받으면 재입력을 요구합니다.
- 직업을 선택하지 않을 경우 전사로 설정됩니다.
=> 시작시 플레이어 데이터 세팅

Text2DBattleGame/Inventory.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Start.cs, Text2DBattleGame/Text2DBattleGame.csproj
=> [feat]아이템창 추가

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/Program.cs
몬스터와 스테이지를 추가하면서 Characters, DisplayBattle, Program 파일에 변경 있습니다 조심하세요!
=> [feat] 몬스터 추가, 스테이지 추가

Text2DBattleGame/DisplayBattle.cs
DisplayBattle파일이 많이 변화했는데 여기서 좀더깔끔하게 더 수정할 계획입니다
=> [refactor] 스킬쓸수있도록 DisplayBattle구조변화

Text2DBattleGame/DisplayBattle.cs
공격 후 취소 누르고 다시 공격해서 모든 몬스터를 죽였을 때 함수 안에 갇히는 버그 수정
=> [fix] 버그 수정 및 자잘한 출력 수정

Text2DBattleGame.sln, Text2DBattleGame/Characters.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Start.cs, Text2DBattleGame/Text2DBattleGame.csproj, Text2DBattleGame/Text2DBattleGame.csproj.user, Text2DBattleGame/packages.config
- Item class를 세분화했습니다.
(todo)확장성을 위함: depth 추가(현재 변수만 보고 어떤 기능인지 판단하기 어려움))
- Json으로 데이터 저장을 위한 조건을 추가했습니다.
=> [fix] Item Class 수정

Text2DBattleGame/DisplayBattle.cs
회피기능추가는 Attack함수만 조금 건들인거라 신경안쓰셔도 될 듯 합니다
다만 Battle함수 출력부분 정리하면서 DisplayPresentStatus(몬스터배열, 플레이어, 앞에숫자를붙일건지아닌지) 함수를 새로 만들었습니다
=> [refactor] Battle출력부분정리 및 회피기능추가

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/DungeonResult.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Text2DBattleGame.csproj, Text2DBattleGame/app.config
=> [fix]Item 오류 수정

Text2DBattleGame/Characters.cs, Text2DBattleGame/Inventory.cs
- 인벤토리 기능을 추가했습니다.
- 플레이어가 같은 종류의 아이템을 중복 장착하려고 하면 장착한 아이템이 자동 해제되고 새로운 아이템이 장착됩니다.
- 포션은 장착할 수 없습니다.
=> [feat] 인벤토리 기능 추가

Text2DBattleGame/Characters.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Start.cs
- 플레이어에 아이템 효과가 보정되지 않은 부분을 수정했습니다.
- 메인 창에서의 오타를 고쳤습니다.
- 인벤토리창에서 선택 사항을 세분화했습니다.
=> 인벤토리 기능 보충

Text2DBattleGame/Characters.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Program.cs
- 플레이어 상태창에 아이템 장착 내역이 포함되도록 수정했습니다.
=> [feat] 플레이어 상태창 기능 추가

Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/SkillManager.cs
=> [fix]아이템 드랍 오류 수정

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Shop.cs, Text2DBattleGame/Start.cs, Text2DBattleGame/Text2DBattleGame.csproj
=> [feature] Shop추가

Text2DBattleGame/AttackItemDataList.json, Text2DBattleGame/Characters.cs, Text2DBattleGame/DefenseItemDataList.json, Text2DBattleGame/Item.cs, Text2DBattleGame/PotionItemDataList.json, Text2DBattleGame/Program.cs, Text2DBattleGame/Start.cs
- JSON Data 형식 수정했습니다.
- 데이터 업데이트 했습니다.
=> [fix] JSON Data 수정

Text2DBattleGame/Characters.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Shop.cs
=> [refactor] 코드 수정

Text2DBattleGame/Start.cs
- 플레이어 이름 입력에 대한 예외처리를 하였습니다.
- 입력값의 앞뒤 공백을 제거합니다.
=> [refactor] 플레이어 이름 입력 예외처리

Text2DBattleGame/Characters.cs, Text2DBattleGame/DisplayBattle.cs, Text2DBattleGame/DungeonResult.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/ItemGroup.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Shop.cs, Text2DBattleGame/SkillManager.cs, Text2DBattleGame/Start.cs
- 주석 제거 및 자잘한 수정
- json data 설정 코드 추가
=> [chore] 주석 수정

Text2DBattleGame/Characters.cs, Text2DBattleGame/DungeonResult.cs, Text2DBattleGame/Inventory.cs, Text2DBattleGame/Item.cs, Text2DBattleGame/Program.cs, Text2DBattleGame/Shop.cs
- item 개수가 추가되었습니다.
- 장착하고 있는 아이템은 잔여 아이템의 개수가 보여집니다.
- 인벤토리 UI를 수정했습니다.
- 아이템 판매의 경우 개수에 상관 없이 한 번에 아이템을 전부 판매합니다.
=> [feat] item 개수 추가
